# Generated by Django 4.2.10 on 2026-03-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên người dùng')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, unique=True, verbose_name='Mã chuyến bay')),
                ('departure_city', models.CharField(max_length=100, verbose_name='Điểm đi')),
                ('destination_city', models.CharField(max_length=100, verbose_name='Điểm đến')),
                ('departure_time', models.DateTimeField(verbose_name='Giờ khởi hành')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá vé (VNĐ)')),
            ],
        ),
    ]
